name: CI

on:
  push:
    branches: [ master ]
    paths: 
      - 'packages/container/**'
  pull_request:
    branches: [ master ]
    paths: 
      - 'packages/container/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!
